# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # 镜像设置。这里使用了镜像。若链接失效则到该链接更新:
  # https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/jammy/
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_url = "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/jammy/20240912/jammy-server-cloudimg-amd64-vagrant.box"

  # 设置内存和CPU数量等
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # 在虚拟机启动时运行的 shell 命令
  config.vm.provision "shell", inline: <<-SHELL
    # 环境安装 - 基本
    apt-get update -y # 更新包列表
    apt-get install -y software-properties-common # 安装基础工具
    apt-get install -y git
    
    # 环境安装 - python
    # PPA方案: https://www.sysgeek.cn/install-python-ubuntu/#0-%E7%AC%AC-1-%E6%AD%A5%EF%BC%9A%E9%80%9A%E8%BF%87-ppa-%E5%AE%89%E8%A3%85-python-312
    sudo add-apt-repository ppa:deadsnakes/ppa # 导入PPA - 仅稳定版本
    sudo apt update # 更新APT缓存
    sudo apt install -y python3.12 python3-pip
    pip3 install jupyter
    # 环境安装 - AI
    # 略

    # 环境安装 - 前端
    # PPA方案
    # 为什么要执行这里的PPA：ubuntu到22也无法直接通过apt安装高版本，最多就到node12，而前端环境一般最少要node18，新一点甚至要node20。将PPA添加到配置中，就可以安装更高的版本
    # 链接失效则到该链接更新: https://deb.nodesource.com/、https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
    sudo apt install -y nodejs
    sudo apt install -y npm
    sudo npm install -g pnpm
    
    # 环境检查 - 版本打印
    cat /etc/issue     # Ubuntu 22.04.5 LTS
    apt --version      # apt 2.4.13 (amd64)
    git --version      # git version 2.34.1
    python3 --version  # (默认) Python 3.10.12
    python3.12 --version # Python 3.12.7
    pip --version      # pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
    jupyter --version  # 
    node --version     # v20.17.0 (注意默认只有12.22.9，完全不够用，要用PPA等方案)
    npm --version      # 10.8.2
    pnpm --version     # 9.12.0
    # 环境检查 - 网络打印
    ping -c 4 www.baidu.com
  SHELL
end